### ISSUE TITLE
Can't build examples "stardogRepo not set"

### ISSUE THREAD

**Issue by porco1x** [clarkparsia/stardog-examples#2]
Whenever I try to build it asks me to set up property stardogRepo in gradle.properties.

Not sure what I'm doign wrong.

**Comment by mhgrove** [comment]
We're in the middle of transitioning the examples for the Stardog 3 release.  At the moment, your best bet is to check out the 2.2.x version of the examples (https://github.com/clarkparsia/stardog-examples/tree/ee40d5cfb88d790402170a1a2e6887a5557cc741).

We will have this sorted out for the release next week.
